#on:
#  push:
#    branches:
#      - master
on:
  workflow_dispatch:
    inputs:
      tmux-version:
        description: 'Which tmux version to build?'
        required: true
        default: '3.3'
jobs:
  build:
    runs-on: ubuntu-latest
    name: build tmux app image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build . -t tmux --build-arg TMUX_TAG=${{ inputs.tmux-version }}
          docker create -ti --name tmuxcontainer tmux bash
          docker cp tmuxcontainer:/opt/releases/tmux-${{ inputs.tmux-version }}-x86_64.AppImage .
#      - name: save artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: tmux.AppImage
#          path: tmux-*.AppImage
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: run-${{ github.run_number }}
          release_name: "Build #${{ github.run_number }}"
          body_path: release.md
          prerelease: false
          draft: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tmux-${{ inputs.tmux-version }}-x86_64.AppImage
          asset_name: tmux-${{ inputs.tmux-version }}-x86_64.AppImage
          asset_content_type: application/octet-stream
